CREATE TABLE IF NOT EXISTS ITEMS(
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT,
CATAGORY_ID TEXT,
UNIT TEXT,
PRICE REAL 
);

INSERT INTO ITEMS(PRODUCT_ID ,PRODUCT_NAME, SUPPLIER_ID, CATAGORY_ID, UNIT, PRICE ) VALUES

('1','CHAIS','1','1','10 BOXES+20 BAGS',18),
('2','CHANG','1','1','24-12 OZ BOTTLES', 19),
('3','ANSEED SYRUP','1','2','12-550 ML BOTTLES',10),
('4','CHEF ATON SEASONING','2','2','48- 6 OZ JARS',22),
('5','CHEF ATON MIX','2','2','36 BOXES',21.35);

SELECT * FROM ITEMS;
SELECT COUNT (PRODUCT_ID) AS PRODUCT_COUNT FROM ITEMS;
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM ITEMS;
SELECT SUM(PRICE) AS TOTAL_PRICE FROM ITEMS;
SELECT * FROM ITEMS WHERE PRODUCT_ID LIKE '1';
SELECT * FROM ITEMS WHERE PRODUCT_NAME LIKE 'ANSEED AYRUP';
SELECT * FROM ITEMS WHERE SUPPLIER_ID LIKE '1';
SELECT * FROM ITEMS WHERE CATAGORY_ID LIKE '2';
SELECT * FROM ITEMS WHERE UNIT LIKE '36 BOXES';
SELECT * FROM ITEMS WHERE PRICE LIKE '21.35';
